server:
  port: 8081
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders:
              - "Content-Type"
              - "Origin"
              - "Accept"
              - "Authorization"
              - "Content-Length"
              - "X-Requested-With"
            allowedOrigins:
              - "*"
              - "http://localhost:4200"
              - "http://angular:4200"
              - "http://157.230.56.211:80"
              - "http://157.230.56.211"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}

        - id: ms-enrollment
          uri: lb://ms-enrollment
          predicates:
            - Path=/enrollment/**
          filters:
            - RewritePath=/enrollment/(?<path>.*), /$\{path}

        - id: ms-files
          uri: lb://ms-files
          predicates:
            - Path=/files/**
          filters:
            - RewritePath=/files/(?<path>.*), /$\{path}

        - id: ms-notification
          uri: lb://ms-notification
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<path>.*), /$\{path}




eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/